require('dotenv').config();
const path=require('path');const fs=require('fs');const express=require('express');const cors=require('cors');const helmet=require('helmet');const morgan=require('morgan');const rateLimit=require('express-rate-limit');const {errorHandler,notFoundHandler}=require('./middleware/errorHandler');
const authRoutes=require('./routes/auth.routes');const productsRoutes=require('./routes/products.routes');const ordersRoutes=require('./routes/orders.routes');const lcRoutes=require('./routes/lc.routes');const walletRoutes=require('./routes/wallet.routes');const paymentsRoutes=require('./routes/payments.routes');const documentsRoutes=require('./routes/documents.routes');const shipmentsRoutes=require('./routes/shipments.routes');const messagesRoutes=require('./routes/messages.routes');const complianceRoutes=require('./routes/compliance.routes');const notificationsRoutes=require('./routes/notifications.routes');const preferencesRoutes=require('./routes/preferences.routes');const locationRoutes=require('./routes/location.routes');const communicationsRoutes=require('./routes/communications.routes');const aiRoutes=require('./routes/ai.routes');const i18nRoutes=require('./routes/i18n.routes');const tradeRoutes=require('./routes/trade.routes');const marketplaceRoutes=require('./routes/marketplace.routes');const mediaRoutes=require('./routes/media.routes');const storefrontAdminRoutes=require('./routes/storefront-admin.routes');const marketMediaRoutes=require('./routes/market-media.routes');const atlasRoutes=require('./routes/atlas.routes');
const app=express();app.set('trust proxy',1);try{const nodemailer=require('nodemailer');const original=nodemailer.createTransport.bind(nodemailer);nodemailer.createTransport=(options={},...rest)=>original({connectionTimeout:10000,greetingTimeout:10000,socketTimeout:15000,...options},...rest)}catch(_){}
const workspaceRoot=path.resolve(__dirname,'..');const frontendEntry=path.join(workspaceRoot,'frontend-v3.html');const intelligenceWidget=fs.readFileSync(path.join(__dirname,'vtg-trade-intelligence.js'),'utf8');const marketplaceWidget=fs.readFileSync(path.join(__dirname,'vtg-marketplace-ui.js'),'utf8');const atlasWidget=fs.readFileSync(path.join(workspaceRoot,'vtg-atlas-ui.js'),'utf8');
app.use(helmet({contentSecurityPolicy:{useDefaults:false,directives:{defaultSrc:["'self'"],scriptSrc:["'self'","'unsafe-inline'",'https://unpkg.com'],styleSrc:["'self'","'unsafe-inline'",'https://fonts.googleapis.com','https://unpkg.com'],imgSrc:["'self'",'data:','blob:','https://images.unsplash.com','https://*.tile.openstreetmap.org'],fontSrc:["'self'",'https://fonts.gstatic.com','data:'],connectSrc:["'self'",'https://api.frankfurter.app','https://open.er-api.com','https://api.coingecko.com','https://news.google.com','https://nominatim.openstreetmap.org','https://*.tile.openstreetmap.org','https://tiles.openfreemap.org'],objectSrc:["'none'"],baseUri:["'self'"],formAction:["'self'"]}}}));
const allowedOrigins=(process.env.CORS_ORIGIN||'').split(',').map(x=>x.trim()).filter(Boolean);if(process.env.NODE_ENV==='production'&&allowedOrigins.length===0)throw new Error('CORS_ORIGIN is required in production.');app.use(cors({origin(origin,callback){if(!origin)return callback(null,true);if(allowedOrigins.includes('*')&&process.env.NODE_ENV!=='production')return callback(null,true);return callback(null,allowedOrigins.includes(origin));}}));app.use(express.json({limit:'2mb'}));app.use(morgan(process.env.NODE_ENV==='production'?'combined':'dev'));app.use(rateLimit({windowMs:15*60*1000,max:600,standardHeaders:true,legacyHeaders:false}));
const authLimiter=rateLimit({windowMs:15*60*1000,max:30,standardHeaders:true,legacyHeaders:false,message:{error:{code:'RATE_LIMITED',message:'Too many attempts. Try again later.'}}});app.get('/health',(req,res)=>res.json({status:'ok',time:new Date().toISOString()}));
app.use('/api/auth',authLimiter,authRoutes);app.use('/api/products',productsRoutes);app.use('/api/orders',ordersRoutes);app.use('/api/lc',lcRoutes);app.use('/api/wallet',walletRoutes);app.use('/api/payments',paymentsRoutes);app.use('/api/documents',documentsRoutes);app.use('/api/shipments',shipmentsRoutes);app.use('/api/messages',messagesRoutes);app.use('/api/compliance',complianceRoutes);app.use('/api/notifications',notificationsRoutes);app.use('/api/preferences',preferencesRoutes);app.use('/api/location',locationRoutes);app.use('/api/communications',communicationsRoutes);app.use('/api/i18n',i18nRoutes);app.use('/api/ai',aiRoutes);app.use('/api/trade',tradeRoutes);app.use('/api/marketplace',marketplaceRoutes);app.use('/api/media',mediaRoutes);app.use('/api/storefront-admin',storefrontAdminRoutes);app.use('/api/market',marketMediaRoutes);app.use('/api/atlas',atlasRoutes);
app.get('/',(req,res,next)=>{fs.readFile(frontendEntry,'utf8',(err,html)=>{if(err)return next(err);const script=`<script src="/vtg-map-recovery.js?v=20260815"></script><script src="/vtg-news-image.js?v=20260815"></script><script>${intelligenceWidget}</script><script>${marketplaceWidget}</script><script>${atlasWidget}</script>`;res.type('html').send(html.includes('</body>')?html.replace('</body>',script+'</body>'):html+script)})});app.use(express.static(workspaceRoot,{index:'frontend-v3.html'}));app.use(notFoundHandler);app.use(errorHandler);const PORT=process.env.PORT||4000;if(require.main===module)app.listen(PORT,()=>console.log(`VTG Africa API listening on port ${PORT}`));module.exports=app;
