const buckets = globalThis.__vtgVisualSearchBuckets || (globalThis.__vtgVisualSearchBuckets = new Map());
function allowed(ip){const now=Date.now(),v=buckets.get(ip);if(!v||now-v.start>900000){buckets.set(ip,{start:now,count:1});return true}if(v.count>=12)return false;v.count++;return true}
module.exports=async function(req,res){
res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');
if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({error:{code:'METHOD_NOT_ALLOWED',message:'Use POST to identify a product photo.'}})}
const forwarded=req.headers['x-forwarded-for'];const ip=String(forwarded|| (req.socket&&req.socket.remoteAddress)||'unknown').split(',')[0].trim();if(!allowed(ip))return res.status(429).json({error:{code:'RATE_LIMITED',message:'Too many visual searches. Please wait a few minutes and try again.'}});
const image=req.body&&typeof req.body.image==='string'?req.body.image:'';if(!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(image)||image.length>2000000)return res.status(400).json({error:{code:'INVALID_IMAGE',message:'Please select a valid product photo under about 1.5 MB after compression.'}});
const key=process.env.OPENAI_API_KEY||process.env.VTG_AI_API_KEY;if(!key)return res.status(503).json({error:{code:'VISUAL_SEARCH_NOT_CONFIGURED',message:'Photo search is built, but the server-side AI key is not configured. Please try again later.'}});
const base=(process.env.VTG_AI_BASE_URL||'https://api.openai.com/v1').replace(/\/+$/,'');const model=process.env.VTG_VISION_MODEL||process.env.VTG_AI_MODEL||process.env.OPENAI_MODEL||'gpt-4o-mini';const ctl=new AbortController();const timer=setTimeout(function(){ctl.abort()},25000);let upstream;
try{upstream=await fetch(base+'/chat/completions',{method:'POST',signal:ctl.signal,headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model:model,temperature:0.1,max_tokens:300,messages:[{role:'system',content:'Identify commercial products from photos for B2B catalogue search. Return only valid JSON with keys product (short generic product name), category (short category), keywords (array of 3 to 8 short search terms), brand (string or empty), model (string or empty). Do not guess brand or model unless clearly visible. Do not claim authenticity, quality, certification or supplier. If unclear, use a cautious generic description.'},{role:'user',content:[{type:'text',text:'Identify this product for catalogue search. Focus on generic type and visible model or brand text if legible.'},{type:'image_url',image_url:{url:image,detail:'low'}}]}]})})}catch(e){if(e.name==='AbortError')return res.status(504).json({error:{code:'VISION_TIMEOUT',message:'Photo analysis took too long. Please try again.'}});return res.status(502).json({error:{code:'VISION_CONNECTION_ERROR',message:'The product image service could not be reached. Please try again shortly.'}})}finally{clearTimeout(timer)}
const payload=await upstream.json().catch(function(){return {}});if(!upstream.ok){console.error('VTG visual search provider error:',upstream.status);return res.status(502).json({error:{code:'VISION_PROVIDER_ERROR',message:'The product photo could not be analysed right now. Please try again shortly.'}})}
let raw=payload.choices&&payload.choices[0]&&payload.choices[0].message&&payload.choices[0].message.content;if(Array.isArray(raw))raw=raw.map(function(p){return p.text||''}).join('\n');if(typeof raw!=='string'||!raw.trim())return res.status(502).json({error:{code:'VISION_EMPTY_RESPONSE',message:'No product description was returned. Try a clearer photo.'}});let parsed;try{parsed=JSON.parse(raw.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''))}catch(e){return res.status(502).json({error:{code:'VISION_INVALID_RESPONSE',message:'The product could not be identified reliably. Please try another photo.'}})}const clean=function(v){return typeof v==='string'?v.trim().slice(0,100):''};return res.status(200).json({product:clean(parsed.product),category:clean(parsed.category),keywords:Array.isArray(parsed.keywords)?parsed.keywords.map(clean).filter(Boolean).slice(0,8):[],brand:clean(parsed.brand),model:clean(parsed.model)});
};